name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  APP_ID: mcq-gen
  REGION: asia-south1

jobs:
  # py_test:
  #   runs-on: ubuntu-latest
  #   name: Test - Python
  #   defaults:
  #     run:
  #       working-directory: ./app
  #   steps:
  #     - name: Checkout source repo
  #       uses: actions/checkout@v3
  #     - name: Setup Python 3.8
  #       uses: actions/setup-python@v3
  #       with:
  #         python-version: "3.8"
  #     - name: Decode secrets
  #       run: echo $SERVICE_ACCOUNT_SECRET | base64 -d > secret/serviceAccountKey.json
  #       env:
  #         SERVICE_ACCOUNT_SECRET: ${{ secrets.FB_SA_KEY_JSON }}
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install pylint pytest pytest-cov spacy gdown
  #         pip install -r requirements.txt
  #         python3 -m spacy download en_core_web_lg
  #     - name: Analyze
  #       run: |
  #         pylint $(git ls-files '*.py')
  #     - name: Test
  #       run: |
  #         python -m pytest --cov=./ --cov-report=xml
  #     - name: Upload coverage report to Codecov
  #       uses: codecov/codecov-action@v2
  #       with:
  #         env_vars: OS,PYTHON
  #         fail_ci_if_error: false
  #         flags: unittests
  #         verbose: true

  deploy_container:
    runs-on: ubuntu-latest
    name: Deploy to cloud Run
    # needs: py_test
    if: "contains(github.event.head_commit.message, 'deploy to cloud')"
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
      - name: Decode secrets
        run: echo $SERVICE_ACCOUNT_SECRET | base64 -d > secret/serviceAccountKey.json
        env:
          SERVICE_ACCOUNT_SECRET: ${{ secrets.FB_SA_KEY_JSON }}
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
      - name: Authorize docker push
        run: gcloud auth configure-docker
      - name: Build and push container
        run: |-
          docker build -t gcr.io/${{ secrets.GCP_PRJ_ID }}/${{ env.APP_ID }}:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PRJ_ID }}/${{ env.APP_ID }}:${{ github.sha }}
      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.APP_ID }} --region ${{ env.REGION }} --image gcr.io/${{ secrets.GCP_PRJ_ID }}/${{ env.APP_ID }}:${{ github.sha }} \
          --platform managed --cpu 4 --concurrency 1 --memory 16Gi --min-instances 0 --timeout 60m --port 80 --allow-unauthenticated
